### ISSUE TITLE
Restarts whenever I click anything.

### ISSUE THREAD

**Issue by ajaelephant** [MCMi460/NSO-RPC#25]
"You will need to restart the application in order for the changes to take place. Sorry for the inconvenience."

**Comment by MCMi460** [comment]
This should only occur when you are clicking "Select Profile" or "Revert", and it is intended.
Is this message appearing in any other scenario?

**Comment by ajaelephant** [comment]
no it's not, only when I press those two buttons you mentioned. But the rich presence never shows up. honestly I logged into the account I wanted to rich presence but logged out to do it the correct way (an account that is friends with the intended account) but I haven't gotten it to work once. is there any software that I must download alongside this program to have it work as intended?

**Comment by MCMi460** [comment]
There isn't any software you need to download alongside it. When you log in using your secondary account, do you "Select Profile" on your main account?

**Comment by ajaelephant** [comment]
yes, and then it tells me to restart the software. once i restart nothing  happens, either i'm logged into my main account and have to log out, or i'm logged into my secondary, where i go to select the main profile, restarting the program again..

**Comment by MCMi460** [comment]
Perhaps I made the new "Selecting" system a bit too difficult to interpret.
Whenever you log in with your secondary out (you log out, then restart the app and enter your verification link), it will show you logged in as your secondary account, right? Then, when you click "Select Profile" on your main account, it will restart the application and appear as if you are logged into your main account. This is intentional. You are not actually logged into your main account. In fact, you will see a "Revert" button highlighted near the bottom of the Profile page. This means you are simply selecting your main account for use with Discord Rich Presence. You are technically still logged in as your secondary account. When you click on your friends list, you will still only be able to access friends your secondary account has added.
You are actually now finished with your setup. You can now play any game, and it will appear on your Discord profile as well as update in-app.
Sorry for the confusion. I'll update the README to make more clear instructions in regards to selecting profiles.

**Comment by ajaelephant** [comment]
Nevermind, I have fixed it by reinstalling discord

**Comment by MCMi460** [comment]
I see. I don't know why it didn't work the first time.
Thanks for documenting this!
