### ISSUE TITLE
doesnt show my activity

### ISSUE THREAD

**Issue by LewiFF** [MCMi460/NSO-RPC#26]
Hey, the issue is that my activity isnt showing when im in a game, but my friends activity show up but mine dont if you have any advice that will be great. Thank You !

**Comment by MCMi460** [comment]
This would be thanks to issue #13. Due to changes in Nintendo's API, you must have two accounts that are friended with each other in order to receive the presence data of either. The README's quickstart guide addresses this, and so does issue #25.
All of it basically just boils down to this: Log in with your secondary account that is friended with your main account, then enter the friends list, click your main account, and choose "Select Profile".
After the app restarts, it should show your main account as your profile, and the presence data will come through properly.

**Comment by LewiFF** [comment]
It still shows my main accounts friends
