### ISSUE TITLE
Status not updating on NSO-RPC start

### ISSUE THREAD

**Issue by EricHerboso** [MCMi460/NSO-RPC#4]
My status in Discord is not updating after installing version 1.1 of NSO-RPC on MacOS 12.2.1.

After failing to update, I closed NSO-RPC and Discord, then deleted the NSO-RPC folder in the local documents folder. Then, with my Switch open and in a game, I opened Discord fully. Then I opened NSO-RPC. It prompted me (as shown in the directions) to give the url taken by right-clicking on the Nintendo app permissions page. My understanding is that at this point it should update within a minute, but after several minutes nothing updates in Discord for me.

Note that at no point have I gotten this to work on my machine. I've confirmed that NSO-RPC is open on the tray, with a checkmark next to "Discord", and that Discord was open prior to starting NSO-RPC. Is there anything else I can do to troubleshoot this?

**Comment by MCMi460** [comment]
Since you're on MacOS, try running this:
```sh
cd ~/Documents
mkdir test12323 && cd test12323
git clone https://github.com/MCMi460/NSO-RPC
cd NSO-RPC/client
python3 -m venv venv
source venv/bin/activate
python -m pip install pypresence requests
python cli.py
```
This will just create a directory in your Documents folder called "test12323" (tried to find a folder name I knew you didn't already have), then it will clone this repository, download some requirements, and run the command-line version of the app.
Please tell me if you get any errors.
