### ISSUE TITLE
Upgrade to pyqt6

### ISSUE THREAD

**Issue by MichaelGDev48** [MCMi460/NSO-RPC#43]
Is there any particular reason we are staying on pyqt5?

**Comment by MCMi460** [comment]
I think I initially had some issues with using pyqt6 on my M1 Mac, so I just defaulted back to pyqt5 which has worked for me in the past. I'll look into updating this soon, if you'd like.

**Comment by DarthNihilus1** [comment]
Ah ok if I were to try to contribute and fork what would be a good replacement for qtwidgets

**Comment by MCMi460** [comment]
I can't find any myself, but there appears to be a PR on the qtwidgets Github page (pythonguis/python-qtwidgets#5) which may work as an alternative. However, it has been over a year and a half since the repository has last been updated, I wouldn't get my hopes up that the PR would be merged anytime soon.
Instead of qtwidgets, you could just change it to be a QPushButton that changes color upon being clicked, or just try to implement your own version of a similar toggle switch.
I'm not sure exactly what the advantages of using PyQt6 over PyQt5 is, but if you'd really like, I can attempt to port it over whenever I have free time next week.

**Comment by MCMi460** [comment]
Since this seems nigh impossible (for the lazy such as I), I will avoid doing this as soon as possible. Thank you for the suggestion, though. If PyQt5 becomes outdated enough to begin causing problems for some users (or PyInstaller breaks it), then I will consider updating to PyQt6 and re-implementing qtwidgets of my own accord, but until then, this will probably not come to fruition.
