### ISSUE TITLE
Universal2 build for MacOS

### ISSUE THREAD

**Issue by DarthNihilus1** [MCMi460/NSO-RPC#44]
Right now the current release is intel only. Are there any plans to have a precompiled build for universal2 (arm64 and intel)

**Comment by DarthNihilus1** [comment]
Ok I managed to build an arm64 build for mac for the latest release (1.3.3) where would i share it?

**Comment by MCMi460** [comment]
Uh, so this is kind of an interesting question, since I actually use an arm64/M1 Mac Mini for development, and I only use my Intel Mac for compiling and releasing new builds because all Macs can run the Intel builds (via Rosetta 2 if not natively).
Normally, I'd also publish a Mac arm64 build, but for whatever reason, py2app seems to be bloating arm64 builds up to 300mb in size, and I'd really prefer not to upload those as releases on Github when performance with Intel builds is only minutely impacted on the M1s.
If your builds as Universal aren't hitting ~300mb, then please update me on this so I can see what I can do to fix this and start publishing arm builds as well.
Also it's like 1am over here, so sorry again if my speech is incoherent or worse.

**Comment by DarthNihilus1** [comment]
Oh yeah i am seeing the same problem with 300 mb , no idea whats causing it , atm i dont mind it so ill just keep it for myself xD 
No clue how to build a universal app with py2app though :/

**Comment by MCMi460** [comment]
So long as it doesn't change the loading speeds too majorly, I'm going to keep building primarily the Intel builds so as to avoid posting ~300mb files on Github releases. Thank you for the suggestion, though, and I'll look into more compact builds for Universal.
