### ISSUE TITLE
NSO-RPC Connects to account, but shows me as “offline”

### ISSUE THREAD

**Issue by DarkKryo** [MCMi460/NSO-RPC#65]
So, NSO-RPC connects to my account just fine. Only problem is that it states that I am offline, even though my switch has an internet connection, and all my Activity settings are set to be visible by everyone. I couldn't find anything similar in the QnA so I thought I'd give asking here a shot.

**Comment by MCMi460** [comment]
Did you login with your secondary account?
#13, #15, #16, #26, #31, and #41 all describe this issue. At the top of the [README](https://github.com/MCMi460/NSO-RPC#quickstart-guide), it is explained that you need to link a secondary account in order to receive your own personal presence. That means you will have to log in with an account that is not your intended main account but is friended with it instead, and then use the "Friend List" feature to click on your main account and press the button that says "Select Profile". This is also detailed in the [README](https://github.com/MCMi460/NSO-RPC#quickstart-guide) and the issues I mentioned above.

Sorry again for the inconvenience; originally, the application did not require these annoying work-around steps, but Big Brother Nintendo did not like us doing that.
I'm going to keep this issue open in case you still have any questions or troubles. Thank you again for your patience!
